// +build generate

package main

import (
	"bytes"
	"io"
	"io/ioutil"
	"log"
	"net/http"
)

func gen() error {
	resp, err := http.Get("https://raw.githubusercontent.com/gopherjs/gopherjs/master/README.md")
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	io.WriteString(&buf, `---
# generated by generate.go; DO NOT EDIT
layout: index
title: Home
permalink: /
---

`)
	_, err = buf.Write(body)
	if err != nil {
		return err
	}

	ioutil.WriteFile("index.md", buf.Bytes(), 0644)

	return nil
}

func main() {
	err := gen()
	if err != nil {
		log.Fatalln(err)
	}
}
